use_frameworks!

platform :ios, '9.0'

target 'MinewBeaconScan_Example' do
  pod 'MinewBeaconScan', :path => '../'

  target 'MinewBeaconScan_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
